builds:
  - binary: chgmd5
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=mod

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: chgmd5
    homepage: https://github.com/dinglevin/levin-pub-tools/appendstr
    tap:
      owner: dinglevin
      name: homebrew-dinglevin
    commit_author:
      name: dinglevin
      email: dinglevin@foxmail.com
  - name: getlastn
    homepage: https://github.com/dinglevin/levin-pub-tools/getlastn
    tap:
      owner: dinglevin
      name: homebrew-dinglevin
    commit_author:
      name: dinglevin
      email: dinglevin@foxmail.com

checksum:
  name_template: 'checksum.txt'
