project_name: levin-pub-tools
builds:
  - main: getlastn/main.go
    id: getlastn
    binary: getlastn
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=readonly

  - main: appendstr/main.go
    id: appendstr
    binary: appendstr
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=readonly

release:
  prerelease: auto

universal_binaries:
  - replace: true
  - id: appendstr
    name_template: appendstr
  - id: getlastn
    name_template: getlastn

brews:
  - name: getlastn
    homepage: https://github.com/dinglevin/levin-pub-tools/getlastn
    tap:
      owner: dinglevin
      name: homebrew-dinglevin
    commit_author:
      name: dinglevin
      email: dinglevin@foxmail.com

checksum:
  name_template: 'checksum.txt'
